modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/Fourmisain/KeepHeadNames/issues"
license = "MIT"

[[mods]]
modId = "keepheadnames"
version = "${version}"
displayName = "Keep Head Names"
authors = "Fourmisain"
description = '''
Keep display names and lore tags of player heads (fix MC-174496)
'''
logoFile = "icon.png"

[[dependencies.keepheadnames]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.keepheadnames]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,1.18)"
ordering = "NONE"
side = "BOTH"