modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Fourmisain/KeepHeadNames/issues"
license = "MIT"

[[mods]]
modId = "keepheadnames"
version = "${mod_version}"
displayName = "Keep Head Names"
authors = "Fourmisain"
description = '''
Keep display names and lore tags of player heads (fix MC-174496)
'''
logoFile = "icon.png"
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.keepheadnames]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2.84,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.keepheadnames]]
modId = "minecraft"
mandatory = true
versionRange = "${neoforge_game_version_range}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${mod_id}.mixins.json"
